# Generated by Django 4.1 on 2023-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_product_comments_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='bid',
            new_name='max_bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='number_bids',
            field=models.IntegerField(default=0),
        ),
    ]
