# Generated by Django 4.1 on 2023-01-19 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bid_bids_max_bid_bids_number_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
