# Generated by Django 4.1 on 2023-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='images/placeholder.svg', upload_to='images'),
        ),
    ]
