# Generated by Django 4.1 on 2022-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_date_alter_comments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(default=None, upload_to='./media/'),
        ),
    ]
