# Generated by Django 4.1 on 2023-01-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='/media/images/oscar.jpg', upload_to='images'),
        ),
    ]
