# Generated by Django 4.1 on 2022-08-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('ART', 'Art'), ('CLOTHING', 'Clothing'), ('TOYS', 'Toys'), ('BOOKS, MOVIES, MUSIC', 'Books, Movies, Music'), ('HEALTH, BEAUTY', 'Health, Beauty'), ('PET SUPPLIES', 'Pet Supplies'), ('NONE', 'None')], default='NONE', max_length=25),
        ),
    ]
