# Generated by Django 4.1 on 2022-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('ELECTRONICS', 'Electronics'), ('ART', 'Art'), ('CLOTHING', 'Clothing'), ('TOYS', 'Toys'), ('BOOKS, MOVIES, MUSIC', 'Books, Movies, Music'), ('HEALTH, BEAUTY', 'Health, Beauty'), ('PET SUPPLIES', 'Pet Supplies')], default='NONE', max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
