# Generated by Django 4.1 on 2023-01-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='date',
        ),
    ]
